### ISSUE TITLE
Since the new facebook layout this extension isn't working properly

### ISSUE THREAD

**Issue by ewok200909** [asadman1523/Hidden-Reactions-for-facebook#1]
Hi!

I have installed your extension and its working with some posts but others are still showing a single reaction, (sometimes happy, angry etc). It would be great if you could update it as this extension would be extremely useful for me just showing likes.

I cannot stand the reactions and the way people abuse the laughing reaction to be nasty, its stopping me using facebook its gotten so bad. Please let me know if there's anything you can do

Thanks!

**Comment by asadman1523** [comment]
Hi, 
Thank you for your ask. I just upload new version 6.0 and it has an option which can hide all reactions. 
Please enjoy the extension.
